include:
  - project: 'plan.one/templates'
    file: '.docker-workflow-template.yml'
    ref: 'v3.1.0'

stages:
  - lint
  - docker build
  - docker push

docker:lint:
  stage: lint
  extends:
    - .docker:lint

docker:build:
  stage: docker build
  extends:
    - .docker:build

docker:push:develop:
  stage: docker push
  extends:
    - .docker:push
  only:
    - develop
  variables:
    IMAGE_TAG: develop

docker:push:latest:
  stage: docker push
  extends:
    - .docker:push
  only:
    - master
  variables:
    IMAGE_TAG: latest

docker:push:tag:
  stage: docker push
  extends:
    - .docker:push
  only:
    - tags
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
