include:
  - project: 'plan.one/templates'
    file: '.docker-workflow-template.yml'
    ref: 'v2.0.0'

stages:
  - lint
  - docker build
  - docker push

docker:lint:
  extends:
    - .docker:lint

docker:build:
  extends:
    - .docker:build

docker:push:develop:
  extends:
    - .docker:push
  only:
    - develop
  variables:
    IMAGE_TAG: develop

docker:push:latest:
  extends:
    - .docker:push
  only:
    - master
  variables:
    IMAGE_TAG: latest
